//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iskur_Ef.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HESAP
    {
        public int HESAP_ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public int HESAP_NO { get; set; }
        public int BAKIYE { get; set; }
    }
}
